from types import SimpleNamespace

import medagent.pipeline.orchestrator as orchestrator_module
import medagent.reporting.project_report as project_report_module
from medagent.core.config import Settings
from medagent.db.models import AgentRun, Base, Molecule, Project, Ranking
from medagent.domain.schemas import (
    AgentMoleculeCandidate,
    AgentResult,
    RunPlan,
    RunPlanAgentConfig,
    RunPlanEvaluation,
    RunPlanStopping,
)
from medagent.db.session import build_engine, build_session_factory
from medagent.pipeline.orchestrator import PipelineOrchestrator


def _session_factory(tmp_path):
    settings = Settings(database_url=f"sqlite:///{tmp_path / 'test.db'}")
    engine = build_engine(settings)
    Base.metadata.create_all(bind=engine)
    return settings, build_session_factory(settings)


def _crem_only_run_plan(
    synthesis_route_scope: str,
    *,
    max_rounds: int,
    top_n: int,
) -> RunPlan:
    return RunPlan(
        status="approved",
        objective="Optimize seed molecules over iterative rounds.",
        max_rounds=max_rounds,
        agents={
            "reinvent4": RunPlanAgentConfig(
                enabled=False,
                role="Global exploration",
                budget="low",
                requested_count=0,
            ),
            "crem": RunPlanAgentConfig(
                enabled=True,
                role="Local SAR edits around top seeds",
                budget="low",
                requested_count=1,
            ),
            "autogrow4": RunPlanAgentConfig(
                enabled=False,
                role="Docking-guided optimization",
                budget="low",
                requested_count=0,
            ),
        },
        evaluation=RunPlanEvaluation(
            mode="fast",
            top_n=top_n,
            use_docking=False,
            use_admet=True,
            use_synthesis=True,
            synthesis_route_scope=synthesis_route_scope,
            use_filters=True,
        ),
        stopping=RunPlanStopping(
            min_score_improvement=0,
            max_total_molecules=20,
            max_tool_failures=3,
        ),
    )


def _patch_iterative_dependencies(
    monkeypatch,
    assessment_calls,
    final_route_calls,
    *,
    top_scores_by_round=None,
):
    generated_by_round = {
        1: "CCN",
        2: "CCC",
        3: "CCO",
    }

    def fake_run_generation_agent(task):
        return AgentResult(
            agent=task.agent,
            round=task.round,
            success=True,
            status="completed",
            molecules=[
                AgentMoleculeCandidate(
                    smiles=generated_by_round.get(task.round, "CCCC"),
                    rationale="Generated by test agent",
                    provenance={"source_strategy": task.agent},
                )
            ],
            warnings=[],
        )

    def fake_assessment(db, project, **kwargs):
        assessment_calls.append(kwargs)
        top_score = (
            top_scores_by_round[len(assessment_calls) - 1]
            if top_scores_by_round and len(assessment_calls) <= len(top_scores_by_round)
            else 100.0 + len(assessment_calls)
        )
        db.query(Ranking).filter_by(project_id=project.project_id).delete()
        for rank, molecule_id in enumerate(kwargs["molecule_ids"], start=1):
            db.add(
                Ranking(
                    project_id=project.project_id,
                    molecule_id=molecule_id,
                    rank=rank,
                    pro_score=90.0,
                    con_score=5.0,
                    evidence_confidence=0.8,
                    overall_score=top_score - rank + 1,
                    final_decision="advance",
                    score_breakdown={"source": "test_assessment"},
                )
            )
        db.commit()
        return {
            "assessed_count": len(kwargs["molecule_ids"]),
            "external_synthesis_routes_enabled": kwargs["enable_external_synthesis_routes"],
        }

    def fake_run_project_synthesis(db, project, molecules, *_args, **_kwargs):
        final_route_calls.append([molecule.molecule_id for molecule in molecules])
        return SimpleNamespace(as_dict=lambda: {"route_count": len(molecules)})

    monkeypatch.setattr(orchestrator_module, "collect_generation_seed_smiles", lambda *_args, **_kwargs: ["CCO"])
    monkeypatch.setattr(orchestrator_module, "run_generation_agent", fake_run_generation_agent)
    monkeypatch.setattr(orchestrator_module, "validate_project_molecules", lambda *_args, **_kwargs: {"validated_count": 1})
    monkeypatch.setattr(orchestrator_module, "filter_project_molecules", lambda *_args, **_kwargs: {"passed_count": 1})
    monkeypatch.setattr(orchestrator_module, "project_docking_config", lambda *_args, **_kwargs: {})
    monkeypatch.setattr(orchestrator_module, "run_project_candidate_assessment", fake_assessment)
    monkeypatch.setattr(orchestrator_module, "generate_project_advice", lambda *_args, **_kwargs: {"suggestions": [], "next_round_constraints": []})
    monkeypatch.setattr(orchestrator_module, "candidate_assessment_tool_status", lambda: {})
    monkeypatch.setattr(orchestrator_module, "run_project_synthesis", fake_run_project_synthesis)
    monkeypatch.setattr(
        orchestrator_module,
        "generate_project_rankings",
        lambda _db, _project, **kwargs: SimpleNamespace(
            as_dict=lambda: {"ranking_count": len(kwargs.get("molecules") or [])}
        ),
    )


def test_iterative_run_assesses_each_round_and_runs_final_synthesis_routes_only_for_top_n(
    tmp_path,
    monkeypatch,
):
    settings, session_factory = _session_factory(tmp_path)
    assessment_calls = []
    final_route_calls = []
    _patch_iterative_dependencies(monkeypatch, assessment_calls, final_route_calls)

    with session_factory() as db:
        project = Project(
            project_id="PROJ-ITERATIVE-FINAL",
            name="Iterative final routes",
            objective="Optimize seed",
        )
        db.add(project)
        db.commit()

        runs = PipelineOrchestrator(settings).run_iterative(
            db,
            project,
            _crem_only_run_plan("final_round_top_n", max_rounds=2, top_n=1),
        )

        agent_names = [run.agent_name for run in runs]
        saved_orchestrator_run = (
            db.query(AgentRun)
            .filter_by(project_id=project.project_id, agent_name="iterative_orchestrator_agent")
            .one()
        )
        db.refresh(project)

    assert "iterative_orchestrator_agent" in agent_names
    assert agent_names.count("crem_agent") == 2
    assert "molecule_narrative_agent" in agent_names
    assert "final_report_agent" in agent_names
    assert [call["enable_external_synthesis_routes"] for call in assessment_calls] == [
        False,
        False,
    ]
    assert len(final_route_calls) == 1
    assert len(final_route_calls[0]) == 1
    assert project.status == "iterative_completed"
    assert project.constraints_json["run_plan"]["status"] == "completed"
    assert saved_orchestrator_run.status == "completed"
    assert saved_orchestrator_run.output_json["final_synthesis_routes"]["scope"] == "final_round_top_n"


def test_iterative_run_allows_every_round_synthesis_routes_without_final_rerun(
    tmp_path,
    monkeypatch,
):
    settings, session_factory = _session_factory(tmp_path)
    assessment_calls = []
    final_route_calls = []
    _patch_iterative_dependencies(monkeypatch, assessment_calls, final_route_calls)

    with session_factory() as db:
        project = Project(
            project_id="PROJ-ITERATIVE-EVERY",
            name="Iterative every-round routes",
            objective="Optimize seed",
        )
        db.add(project)
        db.commit()

        PipelineOrchestrator(settings).run_iterative(
            db,
            project,
            _crem_only_run_plan("every_round_top_n", max_rounds=1, top_n=1),
        )

    assert [call["enable_external_synthesis_routes"] for call in assessment_calls] == [True]
    assert final_route_calls == []


def test_iterative_run_does_not_stop_on_score_drop_when_improvement_stop_disabled(
    tmp_path,
    monkeypatch,
):
    settings, session_factory = _session_factory(tmp_path)
    assessment_calls = []
    final_route_calls = []
    _patch_iterative_dependencies(
        monkeypatch,
        assessment_calls,
        final_route_calls,
        top_scores_by_round=[100.0, 90.0, 80.0],
    )

    with session_factory() as db:
        project = Project(
            project_id="PROJ-ITERATIVE-NO-SCORE-STOP",
            name="Iterative no score stop",
            objective="Explore all requested rounds",
        )
        db.add(project)
        db.commit()

        PipelineOrchestrator(settings).run_iterative(
            db,
            project,
            _crem_only_run_plan("disabled", max_rounds=3, top_n=1),
        )

        saved_orchestrator_run = (
            db.query(AgentRun)
            .filter_by(project_id=project.project_id, agent_name="iterative_orchestrator_agent")
            .one()
        )

    numeric_rounds = [
        item
        for item in saved_orchestrator_run.output_json["rounds"]
        if isinstance(item.get("round"), int)
    ]
    assert len(numeric_rounds) == 3
    assert numeric_rounds[1]["score_improvement"] == -10.0
    assert saved_orchestrator_run.output_json["stop_reason"] == "max_rounds_reached"


def test_iterative_run_score_improvement_stop_can_be_enabled(
    tmp_path,
    monkeypatch,
):
    settings, session_factory = _session_factory(tmp_path)
    assessment_calls = []
    final_route_calls = []
    _patch_iterative_dependencies(
        monkeypatch,
        assessment_calls,
        final_route_calls,
        top_scores_by_round=[100.0, 99.0, 98.0],
    )

    with session_factory() as db:
        project = Project(
            project_id="PROJ-ITERATIVE-SCORE-STOP",
            name="Iterative score stop",
            objective="Stop when configured threshold is missed",
        )
        db.add(project)
        db.commit()

        run_plan = _crem_only_run_plan("disabled", max_rounds=3, top_n=1)
        run_plan.stopping.min_score_improvement = 5.0
        PipelineOrchestrator(settings).run_iterative(db, project, run_plan)

        saved_orchestrator_run = (
            db.query(AgentRun)
            .filter_by(project_id=project.project_id, agent_name="iterative_orchestrator_agent")
            .one()
        )

    numeric_rounds = [
        item
        for item in saved_orchestrator_run.output_json["rounds"]
        if isinstance(item.get("round"), int)
    ]
    assert len(numeric_rounds) == 2
    assert numeric_rounds[1]["score_improvement"] == -1.0
    assert saved_orchestrator_run.output_json["stop_reason"] == "min_score_improvement_not_met"


def test_iterative_run_keeps_generation_progress_when_assessment_fails(
    tmp_path,
    monkeypatch,
):
    settings, session_factory = _session_factory(tmp_path)
    assessment_calls = []
    final_route_calls = []
    _patch_iterative_dependencies(monkeypatch, assessment_calls, final_route_calls)

    def failing_assessment(*_args, **_kwargs):
        raise RuntimeError("assessment stalled")

    monkeypatch.setattr(orchestrator_module, "run_project_candidate_assessment", failing_assessment)

    with session_factory() as db:
        project = Project(
            project_id="PROJ-ITERATIVE-PARTIAL-PROGRESS",
            name="Iterative partial progress",
            objective="Persist generation progress before assessment",
        )
        db.add(project)
        db.commit()

        try:
            PipelineOrchestrator(settings).run_iterative(
                db,
                project,
                _crem_only_run_plan("disabled", max_rounds=1, top_n=1),
            )
        except RuntimeError:
            pass

        saved_orchestrator_run = (
            db.query(AgentRun)
            .filter_by(project_id=project.project_id, agent_name="iterative_orchestrator_agent")
            .one()
        )

    assert saved_orchestrator_run.status == "failed"
    rounds = saved_orchestrator_run.output_json["rounds"]
    assert len(rounds) == 1
    assert rounds[0]["stage"] == "assessment"
    assert rounds[0]["agents"][0]["agent"] == "crem"
    assert rounds[0]["agents"][0]["stored_count"] == 1
    assert rounds[0]["stored_molecule_ids"]


def test_project_report_includes_target_and_sar_agent_outputs(tmp_path, monkeypatch):
    _, session_factory = _session_factory(tmp_path)
    monkeypatch.setattr(
        project_report_module,
        "_write_report_file",
        lambda project, report: str(tmp_path / "report.json"),
    )

    with session_factory() as db:
        project = Project(project_id="PROJ-REPORT-AGENTS", name="Agent report")
        db.add(project)
        db.flush()
        db.add_all(
            [
                AgentRun(
                    agent_run_id="RUN-TARGET",
                    project_id=project.project_id,
                    agent_name="target_agent",
                    model_name="rule_based",
                    status="completed",
                    input_json={},
                    output_json={"target_support_score": 0.8},
                ),
                AgentRun(
                    agent_run_id="RUN-SAR",
                    project_id=project.project_id,
                    agent_name="sar_agent",
                    model_name="rule_based",
                    status="completed",
                    input_json={},
                    output_json={"molecules_analyzed": 3},
                ),
            ]
        )
        db.commit()

        report = project_report_module.build_project_report(db, project)

    assert report["target_and_pocket_analysis"]["agent_analysis"]["target_support_score"] == 0.8
    assert report["sar_overview"]["agent_analysis"]["molecules_analyzed"] == 3
