import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Activity, BookOpenText, Box, FlaskConical, GitBranch, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { dataApi, moleculesApi } from '@/api';
import { MoleculeThumbnail } from '@/components/MoleculeThumbnail';
import { PoseViewer } from '@/components/PoseViewer';
import { StatusBadge } from '@/components/StatusBadge';
import { formatNumber, methodLabel } from '@/lib/format';
import type { DockingResult, EvidenceLink, Molecule, MoleculeNarrative, MoleculeProperties } from '@/types/workbench';

type Tab = 'overview' | 'pose' | 'evidence' | 'provenance' | 'narrative';

function JsonRows({ value }: { value: Record<string, unknown> | undefined }) {
  const items = Object.entries(value || {});
  return items.length ? <div className="table-scroll"><table className="data-table"><tbody>{items.map(([key, item]) => <tr key={key}><th style={{ width: '38%' }}>{key}</th><td className="mono" style={{ whiteSpace: 'pre-wrap' }}>{typeof item === 'string' ? item : JSON.stringify(item)}</td></tr>)}</tbody></table></div> : <div className="subtle">未保存额外来源信息。</div>;
}

export function MoleculeDetailPage() {
  const { projectId, moleculeId } = useParams();
  const [tab, setTab] = useState<Tab>('overview');
  const enabled = Boolean(projectId && moleculeId);
  const { data: molecule, error } = useQuery<Molecule, Error>({ queryKey: ['molecule', projectId, moleculeId], queryFn: () => moleculesApi.get(projectId!, moleculeId!), enabled });
  const { data: properties } = useQuery<MoleculeProperties, Error>({ queryKey: ['molecule-properties', projectId, moleculeId], queryFn: () => moleculesApi.properties(projectId!, moleculeId!), enabled, retry: false });
  const { data: dockings = [] } = useQuery<DockingResult[], Error>({ queryKey: ['molecule-docking', projectId, molecule?.round_id], queryFn: () => moleculesApi.docking(projectId!, molecule?.round_id || undefined), enabled: Boolean(projectId && molecule) });
  const { data: evidence = [] } = useQuery<EvidenceLink[], Error>({ queryKey: ['evidence', projectId], queryFn: () => dataApi.evidence(projectId!), enabled: Boolean(projectId) });
  const { data: narrative } = useQuery<MoleculeNarrative, Error>({ queryKey: ['molecule-narrative', projectId, moleculeId], queryFn: () => moleculesApi.narrative(projectId!, moleculeId!), enabled, retry: false });
  const docking = useMemo(() => dockings.find((item) => item.molecule_id === moleculeId), [dockings, moleculeId]);
  const moleculeEvidence = evidence.filter((item) => item.molecule_id === moleculeId && Boolean(item.document_title || item.source || item.content));
  const tabs: Array<[Tab, string]> = [['overview', '概览'], ['pose', '最佳对接构象'], ['evidence', '文献证据'], ['provenance', '来源谱系'], ['narrative', '中文评价']];

  if (error) return <div className="page"><div className="notice notice-danger">{error instanceof Error ? error.message : '无法读取分子详情。'}</div></div>;
  if (!molecule) return <div className="page"><div className="empty-state">正在载入分子详情…</div></div>;
  return <div className="page"><div className="page-heading"><div className="row"><MoleculeThumbnail smiles={molecule.smiles} className="structure-large" /><div><p className="eyebrow">候选分子</p><h1 className="mono">{molecule.molecule_id}</h1><p className="subtle">{methodLabel(molecule.generation_method || molecule.source_agent)} · {molecule.round_id ? `第 ${molecule.round_id} 轮来源` : 'Seed 来源'}</p></div></div><div className="row"><StatusBadge status={molecule.status} /><Link className="button" to={`/projects/${projectId}/rounds/${molecule.round_id}/ranking`}>返回排名</Link></div></div>
    <div className="metric-grid"><div className="metric"><div className="metric-label">分子量</div><div className="metric-value">{formatNumber(properties?.mw, 1)}</div><div className="metric-note">MW</div></div><div className="metric"><div className="metric-label">LogP</div><div className="metric-value">{formatNumber(properties?.logp, 2)}</div><div className="metric-note">理化性质</div></div><div className="metric"><div className="metric-label">Docking</div><div className="metric-value">{formatNumber(docking?.vina_score ?? docking?.docking_score, 2)}</div><div className="metric-note">GNINA / Vina</div></div><div className="metric"><div className="metric-label">最佳 Pose</div><div className="metric-value">{docking?.pose_artifact_available || docking?.pose_file ? '可用' : '未保存'}</div><div className="metric-note">真实构象文件状态</div></div></div>
    <div className="tab-list" style={{ marginTop: 20 }}>{tabs.map(([id, label]) => <button key={id} className={`tab ${tab === id ? 'tab-active' : ''}`} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div style={{ paddingTop: 18 }}>{tab === 'overview' && <div className="two-column"><section className="panel"><div className="panel-header"><div className="row"><FlaskConical size={17} color="#176451" /><h2>结构与理化性质</h2></div></div><div className="panel-body"><div className="field"><label>SMILES</label><textarea value={molecule.smiles} readOnly /></div><div className="table-scroll" style={{ marginTop: 14 }}><table className="data-table"><tbody>{[['TPSA', properties?.tpsa], ['HBD', properties?.hbd], ['HBA', properties?.hba], ['合成复杂度', properties?.sa_score]].map(([label, value]) => <tr key={String(label)}><th>{label}</th><td>{formatNumber(value as number | null | undefined, 2)}</td></tr>)}</tbody></table></div></div></section><section className="panel"><div className="panel-header"><div className="row"><Activity size={17} color="#176451" /><h2>对接与相互作用</h2></div></div><div className="panel-body stack"><div className="row" style={{ justifyContent: 'space-between' }}><span>Vina / docking score</span><strong>{formatNumber(docking?.vina_score ?? docking?.docking_score, 2)}</strong></div><div className="row" style={{ justifyContent: 'space-between' }}><span>CNN 分数</span><strong>{formatNumber(docking?.cnn_score, 3)}</strong></div><div className="row" style={{ justifyContent: 'space-between' }}><span>关键氢键</span><strong>{formatNumber(docking?.key_hbond_count, 0)}</strong></div><div className="row" style={{ justifyContent: 'space-between' }}><span>碰撞数</span><strong>{formatNumber(docking?.clash_count, 0)}</strong></div>{docking?.key_interactions?.length ? <div className="notice">{docking.key_interactions.join('；')}</div> : <div className="subtle">没有保存结构相互作用注释。</div>}</div></section></div>}
      {tab === 'pose' && <div className="split-grid"><section className="panel"><div className="panel-header"><div className="row"><Box size={17} color="#176451" /><h2>最佳 Pose</h2></div><StatusBadge status={docking?.pose_artifact_available || docking?.pose_file ? 'completed' : 'pending'} /></div><div className="panel-body"><PoseViewer projectId={projectId!} moleculeId={moleculeId!} docking={docking} /></div></section><section className="panel"><div className="panel-header"><h2>构象选择依据</h2></div><div className="panel-body stack"><div className="row" style={{ justifyContent: 'space-between' }}><span>所选 Pose</span><strong>{docking?.selected_pose_rank ?? '未报告'}</strong></div><div className="row" style={{ justifyContent: 'space-between' }}><span>候选 Pose 数</span><strong>{docking?.pose_count ?? '未报告'}</strong></div><div className="row" style={{ justifyContent: 'space-between' }}><span>选择方法</span><strong>{docking?.pose_selection_method || '未记录'}</strong></div><div className="notice notice-warning">仅在后端保存真实构象文件时显示三维结果；没有 Pose 文件时页面不会以评分或推断替代三维构象。</div></div></section></div>}
      {tab === 'evidence' && <section className="panel"><div className="panel-header"><div className="row"><BookOpenText size={17} color="#176451" /><h2>论文引用与证据</h2></div><span className="subtle" style={{ margin: 0 }}>仅展示可追溯至项目资料或文献索引的条目。</span></div><div className="panel-body">{moleculeEvidence.length ? moleculeEvidence.map((item) => <article key={item.evidence_id} className="citation"><div className="row-wrap"><span className="badge badge-neutral">{item.claim_type}</span><div className="citation-title">{item.document_title || '项目资料'}</div></div><div className="citation-meta">{item.source || '本地上传资料'}{item.page_number ? ` · 第 ${item.page_number} 页` : ''}{item.section ? ` · ${item.section}` : ''}</div>{item.rationale && <div className="citation-quote">{item.rationale}</div>}{item.content && <div className="citation-quote">{item.content}</div>}</article>) : <div className="empty-state"><BookOpenText size={30} /><div><strong>没有直接文献证据</strong><div>这不代表分子无效，只表示当前项目资料中没有与该分子建立可追溯的论文引用。上传并解析文献后可重新生成证据。</div></div></div>}</div></section>}
      {tab === 'provenance' && <div className="two-column"><section className="panel"><div className="panel-header"><div className="row"><GitBranch size={17} color="#176451" /><h2>生成来源</h2></div></div><div className="panel-body stack"><div className="row" style={{ justifyContent: 'space-between' }}><span>生成方式</span><strong>{methodLabel(molecule.generation_method || molecule.source_agent)}</strong></div><div className="row" style={{ justifyContent: 'space-between' }}><span>Campaign</span><span className="mono">{molecule.campaign_run_id || '未记录'}</span></div><div className="row" style={{ justifyContent: 'space-between' }}><span>所在轮次</span><span className="mono">{molecule.round_id || '初始 Seed'}</span></div><div><div className="subtle">父分子</div><div className="row-wrap" style={{ marginTop: 5 }}>{molecule.parent_molecule_ids?.length ? molecule.parent_molecule_ids.map((id) => <span className="badge badge-neutral mono" key={id}>{id}</span>) : <span className="badge badge-neutral">初始 Seed</span>}</div></div></div></section><section className="panel"><div className="panel-header"><h2>Provenance 元数据</h2></div><div className="panel-body"><JsonRows value={molecule.provenance_json} /></div></section></div>}
      {tab === 'narrative' && <section className="panel"><div className="panel-header"><div className="row"><ShieldCheck size={17} color="#176451" /><h2>Agent 中文评价</h2></div></div><div className="panel-body">{narrative ? <div className="section-stack"><p style={{ margin: 0, fontSize: 14, lineHeight: 1.75 }}>{narrative.summary}</p>{narrative.why_it_matters && <div className="notice">{narrative.why_it_matters}</div>}<div className="three-column"><div><h3>优势</h3><div className="stack" style={{ marginTop: 8 }}>{narrative.strengths.map((item, index) => <div className="subtle" key={index}>{item}</div>)}</div></div><div><h3>风险</h3><div className="stack" style={{ marginTop: 8 }}>{narrative.risks.map((item, index) => <div className="subtle" key={index}>{item}</div>)}</div></div><div><h3>下一轮建议</h3><div className="stack" style={{ marginTop: 8 }}>{narrative.next_round_suggestions.map((item, index) => <div className="subtle" key={index}>{item}</div>)}</div></div></div></div> : <div className="subtle">尚未生成该分子的中文评价。评价生成后会明确标注计算依据、文献证据和不确定性。</div>}</div></section>}</div>
  </div>;
}
