import { useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Database, FilePlus2, Files, FlaskConical, LoaderCircle, Upload } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { dataApi, moleculesApi, roundsApi } from '@/api';
import { EmptyState } from '@/components/EmptyState';
import { StatusBadge } from '@/components/StatusBadge';
import { formatDate } from '@/lib/format';
import type { ProjectResource, ProjectRound, RagDocument, TargetLigand, UploadedFile } from '@/types/workbench';

export function ProjectDataPage() {
  const { projectId } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const inputRef = useRef<HTMLInputElement>(null);
  const [progress, setProgress] = useState<number | null>(null);
  const { data: files = [] } = useQuery<UploadedFile[], Error>({ queryKey: ['files', projectId], queryFn: () => dataApi.files(projectId!), enabled: Boolean(projectId) });
  const { data: resources = [] } = useQuery<ProjectResource[], Error>({ queryKey: ['resources', projectId], queryFn: () => dataApi.resources(projectId!), enabled: Boolean(projectId) });
  const { data: ligands = [] } = useQuery<TargetLigand[], Error>({ queryKey: ['target-ligands', projectId], queryFn: () => dataApi.ligands(projectId!), enabled: Boolean(projectId) });
  const { data: documents = [] } = useQuery<RagDocument[], Error>({ queryKey: ['documents', projectId], queryFn: () => dataApi.documents(projectId!), enabled: Boolean(projectId) });
  const { data: rounds = [] } = useQuery<ProjectRound[], Error>({ queryKey: ['rounds', projectId], queryFn: () => roundsApi.list(projectId!), enabled: Boolean(projectId) });
  const upload = useMutation<UploadedFile, Error, File>({ mutationFn: (file) => dataApi.upload(projectId!, file, setProgress), onSuccess: () => { setProgress(null); queryClient.invalidateQueries({ queryKey: ['files', projectId] }); } });
  const ingest = useMutation<Record<string, unknown>, Error>({ mutationFn: () => dataApi.ingest(projectId!), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['files', projectId] }); queryClient.invalidateQueries({ queryKey: ['documents', projectId] }); queryClient.invalidateQueries({ queryKey: ['resources', projectId] }); } });
  const importSeeds = useMutation<Record<string, unknown>, Error>({ mutationFn: () => moleculesApi.importSeeds(projectId!), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['project', projectId] }) });
  const createFirstRound = useMutation<ProjectRound, Error>({ mutationFn: () => roundsApi.create(projectId!, { round_number: 1, user_conditions_json: {} }), onSuccess: (round) => { queryClient.invalidateQueries({ queryKey: ['rounds', projectId] }); navigate(`/projects/${projectId}/rounds/${round.round_id}/strategy`); } });
  const chooseFile = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) upload.mutate(file); event.target.value = ''; };

  return <div className="page"><div className="page-heading"><div><p className="eyebrow">项目数据</p><h1>靶点、Seed 与文献资料</h1><p className="subtle">上传内容会进入项目数据上下文，供中枢 Agent 规划策略，并作为分子报告的可追溯引用来源。</p></div>{rounds.length === 0 ? <button className="button button-primary" onClick={() => createFirstRound.mutate()} disabled={createFirstRound.isPending}>{createFirstRound.isPending ? '正在创建…' : '创建第 1 轮策略'} <FlaskConical size={16} /></button> : <button className="button" onClick={() => navigate(`/projects/${projectId}/rounds/${rounds[0].round_id}/strategy`)}>前往当前策略</button>}</div>
    <div className="metric-grid"><div className="metric"><div className="metric-label">已上传文件</div><div className="metric-value">{files.length}</div><div className="metric-note">PDB、SDF、SMI、CSV、PDF、TXT</div></div><div className="metric"><div className="metric-label">项目资源</div><div className="metric-value">{resources.length}</div><div className="metric-note">已解析结构和资源</div></div><div className="metric"><div className="metric-label">已知配体</div><div className="metric-value">{ligands.length}</div><div className="metric-note">内置或靶点相关数据</div></div><div className="metric"><div className="metric-label">文献索引</div><div className="metric-value">{documents.length}</div><div className="metric-note">可供证据引用的资料</div></div></div>
    <div className="split-grid" style={{ marginTop: 18 }}><section className="panel"><div className="panel-header"><div className="row"><Upload size={17} color="#176451" /><h2>上传资料</h2></div></div><div className="panel-body stack"><div className="notice">靶点结构建议上传 PDB；配体支持 SDF、SMI、CSV；论文可上传 PDF、TXT 或 Markdown。上传后执行解析，才会进入策略上下文。</div><input ref={inputRef} type="file" hidden onChange={chooseFile} accept=".pdb,.sdf,.smi,.smiles,.csv,.txt,.md,.pdf" /><button className="button button-primary" onClick={() => inputRef.current?.click()} disabled={upload.isPending}><FilePlus2 size={16} />{upload.isPending ? `上传中 ${progress ?? 0}%` : '选择并上传文件'}</button>{upload.error && <div className="notice notice-danger">{upload.error instanceof Error ? upload.error.message : '上传失败。'}</div>}<div className="row-wrap"><button className="button" onClick={() => ingest.mutate()} disabled={ingest.isPending || files.length === 0}>{ingest.isPending ? <LoaderCircle size={15} className="animate-spin" /> : <Database size={15} />}{ingest.isPending ? '正在解析…' : '解析待处理文件'}</button><button className="button" onClick={() => importSeeds.mutate()} disabled={importSeeds.isPending}><FlaskConical size={15} />导入 Seed 为分子</button></div></div></section>
      <section className="panel"><div className="panel-header"><div className="row"><Files size={17} color="#176451" /><h2>资料完整性</h2></div></div><div className="panel-body stack"><div className="row" style={{ justifyContent: 'space-between' }}><span>靶点结构或资源</span><StatusBadge status={resources.length ? 'completed' : 'pending'} /></div><div className="row" style={{ justifyContent: 'space-between' }}><span>Seed / 相关配体</span><StatusBadge status={ligands.length ? 'completed' : 'pending'} /></div><div className="row" style={{ justifyContent: 'space-between' }}><span>论文与证据资料</span><StatusBadge status={documents.length ? 'completed' : 'pending'} /></div><div className="notice notice-warning">缺少的资料不会阻止你生成策略，但 Agent 会在策略草案中标示数据不足和可能风险。</div></div></section></div>
    <section className="panel" style={{ marginTop: 18 }}><div className="panel-header"><h2>项目文件</h2><span className="subtle" style={{ margin: 0 }}>{files.length} 个文件</span></div>{files.length === 0 ? <EmptyState icon={Files} title="尚未上传项目文件" detail="上传后，解析结果和资料状态将在这里集中显示。" /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>文件</th><th>类型</th><th>解析状态</th><th>上传时间</th></tr></thead><tbody>{files.map((file) => <tr key={file.file_id}><td><strong>{file.filename}</strong></td><td>{file.file_type}</td><td><StatusBadge status={file.parse_status === 'parsed' ? 'completed' : file.parse_status} /></td><td>{formatDate(file.created_at)}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
